---
- name: Create Main Security Group
  ec2_group:
    profile: "{{profile}}"
    description: My Security Group
    vpc_id: "{{ ec2_vpc_id }}"
    region: "{{ aws_region }}"
    tags:
      Name: "{{ ec2_vpc_name }}-sg"
    rules:
      - proto: all
        cidr_ip: 172.0.0.0/16
  register: security_group_details
- name: Store EC2 Group ID.
  set_fact:
    ec2_group_id: "{{security_group_details.group_id}}"
