---
- name: Creating Security Group allowing Kubernetes VPC cidr_ip
  ec2_group:
    name: sg_vpc_cidr
    profile: "{{profile}}"
    description: sg with rule descriptions
    region: us-east-1
    rules:
      - proto: all
        ports:
        - 0
        cidr_ip: 172.20.0.0/16
        
